### ISSUE TITLE
HEAP CORRUPTION DETECTED 

### ISSUE THREAD

**Issue by ted944** [0NG/Format-Preserving-Encryption#3]
I've compiled the example and src using Visual Studio 2010 and linked to the openssl static library. 

I'm getting this error while stepping through the example.cpp (I changed the files to cpp so they will compile with VS 2010) file.
The error happened at line 196 (OPENSSL_free(Bytes);) in ff1.cpp. 

Any idea what caused this?

**Comment by 0NG** [comment]
I tested it with VS2017 and [openSSL on Windows](https://slproweb.com/products/Win32OpenSSL.html), and it works well except that I found a small bug in test.py:smile:.
Could you provide more information, such as what version of openSSL you used? I think maybe the problem was caused by that openSSL.

**Comment by sara-1991** [comment]
hi, 
the code dose not work. it always requesting the file of fpe.h and the compiler says no such a file or directory
could you help me please

**Comment by kar12thik** [comment]
Is there a C++ version i can use to build and check ?

**Comment by 0NG** [comment]
> Is there a C++ version i can use to build and check ?

I think the codes are compatible with C++. Just use any C++ compiler, such as g++. Actually, I used CL in this issue and it succeeded.

**Comment by kar12thik** [comment]
Hey, i am able to run it successfully, do you have the input combinations for text and numeric plaintext along with key,tweak and radix so i can check. Also does it support special characters as plaintext ? How do we address that

**Comment by 0NG** [comment]
@kar12thik 

> do you have the input combinations for text and numeric plaintext along with key,tweak and radix so i can check

All the tests are in [test.py](https://github.com/0NG/Format-Preserving-Encryption/blob/master/test.py). You can also find these from NIST document.

> does it support special characters as plaintext

Yes if you know how ff1/ff3 works. Like [example.c](https://github.com/0NG/Format-Preserving-Encryption/blob/master/example.c), you can choose an appropriate radix and map any character to a number
