### ISSUE TITLE
Not an issue, actually

### ISSUE THREAD

**Issue by polfosol** [0NG/Format-Preserving-Encryption#7]
I just wanted to let you know that I have used some of your test vectors to verify my C-implementation of the FPE algorithms. Of course I have mentioned the source and credit. Please feel free to check out the `testvectors` folder of [this repository](https://github.com/polfosol/micro-AES) and inform me of any issues.

Cheers

**Comment by 0NG** [comment]
Thank you very much! But I think you can directly mention the [NIST documentations](https://csrc.nist.gov/projects/cryptographic-standards-and-guidelines/example-values), since the values are provided by them.😉
